import QRCode from 'qrcode';
import {translations,dishTranslations} from './i18n.js';
const dishes=[
{category:'starters',image:'Crispy Calamari with Lemon and Aioli.png'},
{category:'mains',image:'Golden Prawn Curry with Rice and Salad.png'},
{category:'pasta',image:'Golden Beef Lasagna with Fresh Herb Garnish.png'},
{category:'mains',image:'Tandoori Chicken with Rice and Salad.png'}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let language='en',category='all',diet='all',query='',detailIndex=null,cart={};
try {const saved=localStorage.getItem('beachhut-language');if(translations[saved])language=saved;const stored=JSON.parse(localStorage.getItem('beachhut-cart')||'{}');for(let i=0;i<dishes.length;i++)if(Number.isInteger(stored[i])&&stored[i]>0&&stored[i]<=99)cart[i]=stored[i];document.body.classList.toggle('dark',localStorage.getItem('beachhut-theme')==='dark');}catch{}
const t=key=>translations[language][key]||translations.en[key];
const money=amount=>'Rs '+amount.toFixed(2);
const text=i=>dishTranslations[language][i];
const count=()=>Object.values(cart).reduce((sum,n)=>sum+n,0);
const browseTitles={en:'Browse menu',fr:'Parcourir la carte',es:'Explorar el menú',de:'Menü entdecken',hi:'मेन्यू देखें',zh:'浏览菜单'};
function renderBrowse(){ $('#browse-title').textContent=browseTitles[language]; $('#browse-categories').innerHTML=['starters','mains','pasta'].map(section=>`<button class="browse-category" data-browse="${section}"><span>${t(section)}</span><b>${dishes.filter(d=>d.category===section).length}</b><span aria-hidden="true">↗</span></button>`).join(''); }
document.addEventListener('click',event=>{const button=event.target.closest('[data-browse]');if(!button)return;category=button.dataset.browse;diet='all';query='';$('#dish-search').value='';syncFilters();render();$('#browse-dialog').close();$('#menu').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
function save(){try{localStorage.setItem('beachhut-cart',JSON.stringify(cart))}catch{}}
function quantity(i){return `<div class="quantity">${cart[i]?`<button data-change="${i}" data-step="-1" aria-label="${t('remove')}">−</button><span>${cart[i]}</span><button data-change="${i}" data-step="1" aria-label="${t('add')}">+</button>`:`<button class="add-button" data-change="${i}" data-step="1">${t('add')} ＋</button>`}</div>`}
function render(){const grid=$('#dish-grid');grid.replaceChildren();let visible=0;['starters','mains','pasta'].forEach((section,sectionIndex)=>{const indices=dishes.map((d,i)=>i).filter(i=>(category==='all'||category===section)&&dishes[i].category===section&&diet!=='veg'&&(!query||[...text(i),...dishTranslations.en[i]].join(' ').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase().includes(query.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase())));if(!indices.length)return;visible+=indices.length;const el=document.createElement('section');el.className='menu-section';el.innerHTML=`<div class="category-heading"><span>0${sectionIndex+1}</span><h2>${t(section)}</h2><b>${indices.length}</b></div><div class="cards">${indices.map(i=>`<article class="dish"><div><div class="dish-tag"><span class="diet-symbol" aria-hidden="true">▲</span>${t('nonveg')}${i===1?`<span class="special">${t('favourite')}</span>`:''}</div><h3>${text(i)[0]}</h3><strong class="price">${money(750)}</strong><p class="description">${text(i)[1]}</p><button class="read-more" data-detail="${i}">${t('more')}</button></div><div class="dish-visual"><button class="photo" data-detail="${i}" aria-label="${text(i)[0]}"><img src="${encodeURI(dishes[i].image)}" alt="${text(i)[0]}" loading="lazy"></button>${quantity(i)}</div></article>`).join('')}</div>`;grid.append(el)});$('#result-count').textContent=`${visible} ${t('items')}`;$('#empty-state').hidden=visible!==0;updateCart();}
function updateCart(){const n=count();$('#cart-bar').hidden=!n;$('#floating-count').hidden=!n;$('#floating-count').textContent=n;$('#cart-count').textContent=n;$('#cart-summary').textContent=`${n} ${t('items')} · ${money(n*750)}`;$('#cart-items').innerHTML=n?Object.keys(cart).map(i=>`<div class="cart-item"><img src="${encodeURI(dishes[i].image)}" alt="${text(i)[0]}"><div><h3>${text(i)[0]}</h3><span class="price">${money(cart[i]*750)}</span></div>${quantity(i)}</div>`).join(''):`<p>${t('empty')}</p>`;$('#grand-total').textContent=money(n*750);$('#show-waiter').disabled=!n;$('#clear-cart').disabled=!n;}
function detail(i){detailIndex=i;$('#dish-detail').innerHTML=`<img class="detail-image" src="${encodeURI(dishes[i].image)}" alt="${text(i)[0]}"><h2>${text(i)[0]}</h2><strong class="detail-price">${money(750)}</strong><p>${text(i)[1]}</p><p class="note">${t('allergen')}</p><button class="solid" data-change="${i}" data-step="1">${t('add')} · ${money(750)}</button>`;}
function localize(){document.documentElement.lang=language;$$('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));$('#language-code').textContent=language.toUpperCase();$('#dish-search').placeholder=t('search')+'…';$$('[data-lang]').forEach(el=>el.classList.toggle('active',el.dataset.lang===language));$$('[data-close]').forEach(el=>el.setAttribute('aria-label',t('close')));$('#search-toggle').setAttribute('aria-label',t('search'));$('#language-toggle').setAttribute('aria-label',t('language'));$('#qr-dialog').setAttribute('aria-label',t('qr'));if(['localhost','127.0.0.1',''].includes(location.hostname))$('#qr-status').textContent=t('local');if(detailIndex!==null)detail(detailIndex);render();renderBrowse();}
function syncFilters(){$$('[data-category]').forEach(el=>{el.classList.toggle('active',el.dataset.category===category);el.setAttribute('aria-pressed',String(el.dataset.category===category))});$$('[data-diet]').forEach(el=>{el.classList.toggle('active',el.dataset.diet===diet);el.setAttribute('aria-pressed',String(el.dataset.diet===diet))});}
document.addEventListener('click',event=>{const change=event.target.closest('[data-change]');if(change){const i=Number(change.dataset.change);cart[i]=Math.min(99,Math.max(0,(cart[i]||0)+Number(change.dataset.step)));if(!cart[i])delete cart[i];save();const inCart=change.closest('#cart-dialog');const focusSelector=`[data-change="${i}"][data-step="${change.dataset.step}"]`;render();const scope=inCart?$('#cart-dialog'):$('#dish-grid');scope.querySelector(focusSelector)?.focus();return}const dish=event.target.closest('[data-detail]');if(dish){detail(Number(dish.dataset.detail));$('#dish-dialog').showModal()}});
$$('[data-category]').forEach(el=>el.addEventListener('click',()=>{category=el.dataset.category;syncFilters();render()}));$$('[data-diet]').forEach(el=>el.addEventListener('click',()=>{diet=el.dataset.diet===diet?'all':el.dataset.diet;syncFilters();render()}));
$('#dish-search').addEventListener('input',event=>{query=event.target.value.trim();render()});$('#search-toggle').addEventListener('click',()=>{$('#search-wrap').hidden=!$('#search-wrap').hidden;if(!$('#search-wrap').hidden){$('#dish-search').focus();$('#search-wrap').scrollIntoView({block:'center'})}});$('#search-clear').addEventListener('click',()=>{query='';$('#dish-search').value='';render();$('#dish-search').focus()});$('#reset-filters').addEventListener('click',()=>{category='all';diet='all';query='';$('#dish-search').value='';syncFilters();render()});
const modalBindings={'language-toggle':'language-dialog','filters-open':'filters-dialog','qr-open':'qr-dialog','footer-qr':'qr-dialog','cart-open':'browse-dialog','continue':'cart-dialog'};Object.entries(modalBindings).forEach(([button,dialog])=>$('#'+button).addEventListener('click',()=>$('#'+dialog).showModal()));$('#apply-filters').addEventListener('click',()=>$('#filters-dialog').close());
$$('[data-lang]').forEach(button=>button.addEventListener('click',()=>{language=button.dataset.lang;try{localStorage.setItem('beachhut-language',language)}catch{}localize();$('#language-dialog').close()}));$('#theme-toggle').addEventListener('click',()=>{document.body.classList.toggle('dark');try{localStorage.setItem('beachhut-theme',document.body.classList.contains('dark')?'dark':'light')}catch{}});
$$('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));$$('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}));
$('#clear-cart').addEventListener('click',()=>{cart={};save();render()});$('#show-waiter').addEventListener('click',()=>{$('#waiter-items').innerHTML=Object.keys(cart).map(i=>`<div class="waiter-row"><span>${cart[i]} × ${text(i)[0]}</span><strong>${money(cart[i]*750)}</strong></div>`).join('');$('#waiter-request').textContent=$('#cooking-request').value;$('#waiter-total').textContent=money(count()*750);$('#cart-dialog').close();$('#waiter-dialog').showModal()});
const menuUrl=new URL(location.href);menuUrl.hash='menu';menuUrl.search='';QRCode.toCanvas($('#menu-qr'),menuUrl.href,{width:240,margin:4,errorCorrectionLevel:'M',color:{dark:'#214d40',light:'#ffffff'}}).catch(()=>$('#qr-status').textContent=menuUrl.href);$('#copy-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(menuUrl.href);$('#copy-link').textContent=t('copied');setTimeout(()=>$('#copy-link').textContent=t('copy'),1800)}catch{$('#qr-status').textContent=menuUrl.href}});
localize();syncFilters();renderBrowse();
