const keys=['hero','intro','escape','all','starters','mains','pasta','qr','search','filters','veg','nonveg','noResults','tryAgain','reset','allergen','footer','menu','continue','language','dietNote','apply','scan','copy','order','request','total','orderNote','waiter','clear','selection','add','more','favourite','empty','copied','local','items','close','remove'];
const rows={
en:['A taste of the island.','Fresh flavours. Ocean views. Explore something delicious.','Your seaside escape','All dishes','Starters','Main course','Comfort classics','QR menu','Search dishes','Filters','Veg','Non-veg','No dishes found','Try a different search or clear your filters.','Reset filters','Please ask our team about allergens and dietary requirements.','Sea view dining · Trou aux Biches, Mauritius','Menu','Continue →','Language','Choose a preference to explore the menu.','Apply filters','Scan with your phone’s camera to explore our menu.','Copy menu link','Your order','Add a cooking request (optional)','Items total','Show your selection to your waiter. Orders are confirmed by our team.','Show order to waiter','Clear selection','Your selection','ADD','Read more','Island favourite','Your selection is empty.','Menu link copied','Local preview: publish the site before guests scan this QR.','items','Close','Remove'],
fr:['Les saveurs de l’île.','Saveurs fraîches. Vue sur l’océan. Découvrez un délice.','Votre escale au bord de la mer','Tous les plats','Entrées','Plats principaux','Les classiques','Menu QR','Rechercher un plat','Filtres','Végétarien','Non végétarien','Aucun plat trouvé','Essayez une autre recherche ou effacez les filtres.','Réinitialiser','Consultez notre équipe pour les allergènes et vos besoins alimentaires.','Vue sur mer · Trou aux Biches, Maurice','Carte','Continuer →','Langue','Choisissez une préférence pour explorer la carte.','Appliquer','Scannez avec l’appareil photo de votre téléphone pour découvrir la carte.','Copier le lien','Votre commande','Ajouter une demande de préparation (facultatif)','Total des plats','Présentez votre sélection au serveur. Notre équipe confirme les commandes.','Présenter au serveur','Effacer la sélection','Votre sélection','AJOUTER','En savoir plus','Saveurs de l’île','Votre sélection est vide.','Lien copié','Aperçu local : publiez le site avant de partager ce QR.','plats','Fermer','Retirer'],
es:['El sabor de la isla.','Sabores frescos. Vistas al océano. Descubre algo delicioso.','Tu escapada junto al mar','Todos los platos','Entrantes','Platos principales','Los clásicos','Menú QR','Buscar platos','Filtros','Vegetariano','No vegetariano','No se encontraron platos','Prueba otra búsqueda o borra los filtros.','Restablecer filtros','Consulta a nuestro equipo sobre alérgenos y necesidades alimentarias.','Vistas al mar · Trou aux Biches, Mauricio','Menú','Continuar →','Idioma','Elige una preferencia para explorar el menú.','Aplicar filtros','Escanea con la cámara de tu teléfono para explorar el menú.','Copiar enlace','Tu pedido','Añadir una petición de cocina (opcional)','Total de platos','Muestra tu selección al camarero. Nuestro equipo confirma los pedidos.','Mostrar al camarero','Borrar selección','Tu selección','AÑADIR','Leer más','Favorito de la isla','Tu selección está vacía.','Enlace copiado','Vista local: publica el sitio antes de compartir este QR.','platos','Cerrar','Quitar'],
de:['Der Geschmack der Insel.','Frische Aromen. Meerblick. Entdecke etwas Köstliches.','Deine Auszeit am Meer','Alle Gerichte','Vorspeisen','Hauptgerichte','Die Klassiker','QR-Menü','Gerichte suchen','Filter','Vegetarisch','Nicht vegetarisch','Keine Gerichte gefunden','Versuche eine andere Suche oder lösche die Filter.','Filter zurücksetzen','Bitte frage unser Team nach Allergenen und Ernährungsbedürfnissen.','Meerblick · Trou aux Biches, Mauritius','Menü','Weiter →','Sprache','Wähle eine Vorliebe, um das Menü zu entdecken.','Filter anwenden','Scanne mit deiner Handykamera, um das Menü zu entdecken.','Menülink kopieren','Deine Bestellung','Zubereitungswunsch hinzufügen (optional)','Gesamtsumme','Zeige deine Auswahl der Bedienung. Unser Team bestätigt Bestellungen.','Der Bedienung zeigen','Auswahl löschen','Deine Auswahl','HINZUFÜGEN','Mehr erfahren','Inselfavorit','Deine Auswahl ist leer.','Menülink kopiert','Lokale Vorschau: Veröffentliche die Website vor dem Teilen dieses QR-Codes.','Gerichte','Schließen','Entfernen'],
hi:['द्वीप का स्वाद।','ताज़े स्वाद। समुद्र का नज़ारा। कुछ स्वादिष्ट खोजें।','समुद्र किनारे आपका ठिकाना','सभी व्यंजन','स्टार्टर','मुख्य व्यंजन','पसंदीदा क्लासिक्स','QR मेन्यू','व्यंजन खोजें','फ़िल्टर','शाकाहारी','मांसाहारी','कोई व्यंजन नहीं मिला','दूसरी खोज करें या फ़िल्टर हटाएँ।','फ़िल्टर हटाएँ','एलर्जी और आहार संबंधी ज़रूरतों के लिए हमारी टीम से पूछें।','समुद्र का नज़ारा · ट्रू ऑ बिश, मॉरीशस','मेन्यू','आगे बढ़ें →','भाषा','मेन्यू देखने के लिए अपनी पसंद चुनें।','फ़िल्टर लागू करें','मेन्यू देखने के लिए फ़ोन के कैमरे से स्कैन करें।','मेन्यू लिंक कॉपी करें','आपका ऑर्डर','खाना बनाने का अनुरोध जोड़ें (वैकल्पिक)','कुल राशि','अपना चयन वेटर को दिखाएँ। हमारी टीम ऑर्डर की पुष्टि करेगी।','वेटर को दिखाएँ','चयन हटाएँ','आपका चयन','जोड़ें','और पढ़ें','द्वीप का पसंदीदा','आपका चयन खाली है।','मेन्यू लिंक कॉपी हुआ','स्थानीय पूर्वावलोकन: QR साझा करने से पहले साइट प्रकाशित करें।','व्यंजन','बंद करें','हटाएँ'],
zh:['海岛的味道。','新鲜风味，海洋美景。探索美味佳肴。','您的海滨休憩之地','所有菜品','前菜','主菜','经典美食','二维码菜单','搜索菜品','筛选','素食','非素食','未找到菜品','请尝试其他搜索或清除筛选。','重置筛选','有关过敏原及饮食需求，请咨询我们的团队。','海景餐饮 · 毛里求斯 Trou aux Biches','菜单','继续 →','语言','选择偏好以浏览菜单。','应用筛选','使用手机相机扫描二维码浏览菜单。','复制菜单链接','您的订单','添加烹饪要求（可选）','菜品合计','请向服务员出示您的选择。订单由我们的团队确认。','向服务员出示','清空选择','您的选择','添加','了解更多','海岛人气菜','您尚未选择菜品。','菜单链接已复制','本地预览：请先发布网站再与客人分享二维码。','份','关闭','移除']
};
export const translations=Object.fromEntries(Object.entries(rows).map(([lang,row])=>[lang,Object.fromEntries(keys.map((key,i)=>[key,row[i]]))]));
export const dishTranslations={
en:[['Crispy Calamari','Golden, crispy calamari with lemon and creamy aioli.'],['Golden Prawn Curry','Fragrant prawn curry, served with rice and a fresh salad.'],['Beef Lasagna','Rich beef, pasta, and golden cheese, finished with fresh herbs.'],['Tandoori Chicken','Spiced tandoori chicken with rice and a refreshing salad.']],
fr:[['Calamars croustillants','Calamars dorés et croustillants, citron et aïoli onctueux.'],['Curry de crevettes','Curry de crevettes parfumé, servi avec du riz et une salade fraîche.'],['Lasagnes au bœuf','Bœuf savoureux, pâtes et fromage gratiné, garnis d’herbes fraîches.'],['Poulet tandoori','Poulet tandoori épicé, accompagné de riz et d’une salade fraîche.']],
es:[['Calamares crujientes','Calamares dorados y crujientes con limón y alioli cremoso.'],['Curry de gambas','Curry aromático de gambas con arroz y ensalada fresca.'],['Lasaña de ternera','Ternera, pasta y queso gratinado con hierbas frescas.'],['Pollo tandoori','Pollo tandoori especiado con arroz y ensalada fresca.']],
de:[['Knusprige Calamari','Goldene, knusprige Calamari mit Zitrone und cremiger Aioli.'],['Garnelen-Curry','Duftendes Garnelen-Curry mit Reis und frischem Salat.'],['Rindfleisch-Lasagne','Herzhaftes Rindfleisch, Pasta und goldener Käse mit frischen Kräutern.'],['Tandoori-Hähnchen','Würziges Tandoori-Hähnchen mit Reis und frischem Salat.']],
hi:[['कुरकुरी कैलामारी','नींबू और मलाईदार ऐओली के साथ सुनहरी, कुरकुरी कैलामारी।'],['झींगा करी','चावल और ताज़े सलाद के साथ सुगंधित झींगा करी।'],['बीफ़ लज़ान्या','ताज़ी जड़ी-बूटियों के साथ बीफ़, पास्ता और सुनहरा चीज़।'],['तंदूरी चिकन','चावल और ताज़े सलाद के साथ मसालेदार तंदूरी चिकन।']],
zh:[['香脆鱿鱼','金黄酥脆的鱿鱼，配柠檬和蒜味蛋黄酱。'],['金黄虾咖喱','香浓虾咖喱，配米饭和新鲜沙拉。'],['牛肉千层面','浓郁牛肉、意面和金黄奶酪，点缀新鲜香草。'],['坦都里烤鸡','香料腌制的坦都里烤鸡，配米饭和清爽沙拉。']]
};
